# custom path for swagger-ui
springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-custom.html

    operations-sorter: method

# H2 Related Configurations
spring:
  datasource:
    url: jdbc:h2:mem:springdoc